networks:
  guard-network:
    name: guard-network
    driver: bridge

services:
  pi-guard:
    image: pi-guard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pi-guard
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    depends_on:
      - chromadb
    networks:
      - guard-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - guard-network