# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fml_server.proto\x12\tml_server\"!\n\x11\x45ncodeTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\'\n\x12\x45ncodeTextResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"(\n\x12\x45ncodeImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"(\n\x13\x45ncodeImageResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"/\n\x18\x45ncodeBatchImagesRequest\x12\x13\n\x0bimages_data\x18\x01 \x03(\x0c\"O\n\x19\x45ncodeBatchImagesResponse\x12\x32\n\nembeddings\x18\x01 \x03(\x0b\x32\x1e.ml_server.EncodeImageResponse2\x89\x02\n\x08MLServer\x12K\n\nEncodeText\x12\x1c.ml_server.EncodeTextRequest\x1a\x1d.ml_server.EncodeTextResponse\"\x00\x12N\n\x0b\x45ncodeImage\x12\x1d.ml_server.EncodeImageRequest\x1a\x1e.ml_server.EncodeImageResponse\"\x00\x12`\n\x11\x45ncodeBatchImages\x12#.ml_server.EncodeBatchImagesRequest\x1a$.ml_server.EncodeBatchImagesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODETEXTREQUEST']._serialized_start=30
  _globals['_ENCODETEXTREQUEST']._serialized_end=63
  _globals['_ENCODETEXTRESPONSE']._serialized_start=65
  _globals['_ENCODETEXTRESPONSE']._serialized_end=104
  _globals['_ENCODEIMAGEREQUEST']._serialized_start=106
  _globals['_ENCODEIMAGEREQUEST']._serialized_end=146
  _globals['_ENCODEIMAGERESPONSE']._serialized_start=148
  _globals['_ENCODEIMAGERESPONSE']._serialized_end=188
  _globals['_ENCODEBATCHIMAGESREQUEST']._serialized_start=190
  _globals['_ENCODEBATCHIMAGESREQUEST']._serialized_end=237
  _globals['_ENCODEBATCHIMAGESRESPONSE']._serialized_start=239
  _globals['_ENCODEBATCHIMAGESRESPONSE']._serialized_end=318
  _globals['_MLSERVER']._serialized_start=321
  _globals['_MLSERVER']._serialized_end=586
# @@protoc_insertion_point(module_scope)
