# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_server_pb2 as ml__server__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServerStub(object):
    """The ML Model Serving Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncodeText = channel.unary_unary(
                '/ml_server.MLServer/EncodeText',
                request_serializer=ml__server__pb2.EncodeTextRequest.SerializeToString,
                response_deserializer=ml__server__pb2.EncodeTextResponse.FromString,
                _registered_method=True)
        self.EncodeImage = channel.unary_unary(
                '/ml_server.MLServer/EncodeImage',
                request_serializer=ml__server__pb2.EncodeImageRequest.SerializeToString,
                response_deserializer=ml__server__pb2.EncodeImageResponse.FromString,
                _registered_method=True)
        self.EncodeBatchImages = channel.unary_unary(
                '/ml_server.MLServer/EncodeBatchImages',
                request_serializer=ml__server__pb2.EncodeBatchImagesRequest.SerializeToString,
                response_deserializer=ml__server__pb2.EncodeBatchImagesResponse.FromString,
                _registered_method=True)


class MLServerServicer(object):
    """The ML Model Serving Service
    """

    def EncodeText(self, request, context):
        """1. Embedding Model Endpoint (Single vector output)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeBatchImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncodeText': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeText,
                    request_deserializer=ml__server__pb2.EncodeTextRequest.FromString,
                    response_serializer=ml__server__pb2.EncodeTextResponse.SerializeToString,
            ),
            'EncodeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeImage,
                    request_deserializer=ml__server__pb2.EncodeImageRequest.FromString,
                    response_serializer=ml__server__pb2.EncodeImageResponse.SerializeToString,
            ),
            'EncodeBatchImages': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeBatchImages,
                    request_deserializer=ml__server__pb2.EncodeBatchImagesRequest.FromString,
                    response_serializer=ml__server__pb2.EncodeBatchImagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_server.MLServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml_server.MLServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLServer(object):
    """The ML Model Serving Service
    """

    @staticmethod
    def EncodeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_server.MLServer/EncodeText',
            ml__server__pb2.EncodeTextRequest.SerializeToString,
            ml__server__pb2.EncodeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_server.MLServer/EncodeImage',
            ml__server__pb2.EncodeImageRequest.SerializeToString,
            ml__server__pb2.EncodeImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeBatchImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_server.MLServer/EncodeBatchImages',
            ml__server__pb2.EncodeBatchImagesRequest.SerializeToString,
            ml__server__pb2.EncodeBatchImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
